# Generated by Django 5.1.1 on 2024-10-01 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_rename_date_registration_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportcardimage",
            name="student",
        ),
        migrations.RemoveField(
            model_name="reportcardpdf",
            name="student",
        ),
        migrations.AddField(
            model_name="registration",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.grade",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="report_card_type",
            field=models.CharField(
                choices=[("PDF", "PDF"), ("IMAGES", "Images")],
                default="IMAGES",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="transfer_letter",
            field=models.FileField(null=True, upload_to="transfer_letters/"),
        ),
        migrations.AddField(
            model_name="reportcardimage",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_card_images",
                to="registration.registration",
            ),
        ),
        migrations.AddField(
            model_name="reportcardpdf",
            name="registration",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_card_pdf",
                to="registration.registration",
            ),
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="registration.branch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="registration",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.form",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.form",
            ),
        ),
    ]
