# Generated by Django 5.1.1 on 2024-10-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_remove_reportcardimage_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="desscription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="branch",
            name="students",
            field=models.IntegerField(default=0),
        ),
    ]
