# Generated by Django 5.1.1 on 2024-10-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_branch_desscription_branch_image_branch_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="birth_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="birth_certificates/"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="email",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name="registration",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="last_grade_completed",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="parent_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="previous_school",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="transfer_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="transfer_letters/"
            ),
        ),
    ]
