# Generated by Django 5.1.1 on 2024-10-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_form_class_hours_form_students_count_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="class_hours",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="grade",
            name="students_count",
            field=models.IntegerField(default=50),
        ),
    ]
