# Generated by Django 5.1.1 on 2024-10-03 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_grade_class_hours_grade_students_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjects",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="registration.grade",
            ),
        ),
        migrations.AlterField(
            model_name="subjects",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_subjects",
                to="registration.form",
            ),
        ),
    ]
