# Generated by Django 5.1.1 on 2024-10-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0009_form_registrations_grade_registrations_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="user",
            new_name="student",
        ),
    ]
